# 11. Asigne la variable XSTD al estándar más reciente que soporta su compilador
#, por ejemplo: XSTD=-std=c17` o `XSTD=-std=c20. Para esto indague la versión
# de su compilador (ej.: g++ --version) y aproveche para revisar si soporta
# semáforos contadores.
include ../../../common/Makefile

FLAG += -pthread
XSTD = -std=c++20 # tengo la version 12.2.0 por lo que si aguanta semaphores
